Final/Final/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from istore.views import add_to_cart, cart_view, buy_all
from istore.views import index_view, catalog_view, product_view
from users.views import signup

urlpatterns = [
    path('', index_view, name='index'),
    path('catalog/<int:cat_id>', catalog_view, name='catalog_view'),
    path('catalog/<slug:slug>', product_view, name='product_view'),

    path('cart/', cart_view, name='cart'),
    path('cart/<int:order_id>', buy_all, name='buy_all'),
    path('cart/<slug:slug>', add_to_cart, name='add_to_cart'),

    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('signup/', signup, name="signup"),

    path('admin/', admin.site.urls),
]

# urlpatterns += [
#     path('accounts/', include('django.contrib.auth.urls'))
# ]

Final/istore/models.py
from datetime import datetime

from django.core.validators import MinValueValidator
from django.db import models
from django.utils.text import slugify
from transliterate import translit


class CategoryGroup(models.Model):
    cat_group_name = models.CharField(
        max_length=20,
        verbose_name="Группа товаров",
        null=False,
    )

    def __str__(self):
        return self.cat_group_name


class Category(models.Model):
    group = models.ForeignKey(
        CategoryGroup,
        null=True,
        blank=True,
        default=1,
        on_delete=models.SET_DEFAULT
    )
    cat_name = models.CharField(
        max_length=20,
        verbose_name="Категория товаров",
        null=False,
    )

    def __str__(self):
        return self.cat_name


class Merchandise(models.Model):
    category = models.ForeignKey(
        Category,
        null=False,
        default=0,
        on_delete=models.SET_DEFAULT
    )
    name = models.CharField(
        max_length=20,
        verbose_name="Название",
        null=False,
    )
    price = models.FloatField(
        null=False,
        verbose_name="Цена"
    )
    picture = models.ImageField(
        upload_to='./static/images/istore',
        verbose_name="Фото",
        null=True,
        blank=True
    )
    description = models.TextField(
        verbose_name="Описание"
    )

    slug = models.SlugField(
        null=True,
        blank=True,
        editable=False
    )

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.slug == '':
            self.slug = slugify(translit(self.name, reversed=True))
        super(Merchandise, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Comment(models.Model):
    class Rating(models.IntegerChoices):
        ONE = 1, "★"
        TWO = 2, "★★"
        THREE = 3, "★★★"
        FOUR = 4, "★★★★"
        FIVE = 5, "★★★★★"

    product = models.ForeignKey(
        Merchandise,
        null=False,
        on_delete=models.CASCADE
    )
    author = models.CharField(
        max_length=20,
        verbose_name="Автор",
    )
    rating = models.IntegerField(
        default=Rating.FIVE,
        choices=Rating.choices,
        verbose_name='Оценка'
    )
    comment_text = models.TextField(
        verbose_name="Отзыв"
    )

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

    def __str__(self):
        return f"{self.author}: {self.product}"


class Article(models.Model):
    title = models.CharField(
        max_length=50,
        null=False,
        verbose_name="Название"
    )
    text = models.TextField(
        verbose_name="Текст"

    )
    merch = models.ManyToManyField(
        Merchandise,
        related_name="articles",
        verbose_name="Продукты"
    )

    creation_date = models.DateTimeField(
        null=True,
        blank=True,
        editable=False
    )

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def save(self, *args, **kwargs):
        if not self.creation_date:
            self.creation_date = datetime.now()
        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


class Order(models.Model):
    user = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        null=False
    )
    products = models.ManyToManyField(
        Merchandise,
        related_name='orders',
        through='OrderDetails',
        null=True,
    )
    created = models.DateTimeField(
        auto_now_add=True,
        null=False
    )
    active = models.BooleanField(
        default=True
    )

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f"{self.user.email} {self.created.timestamp()}"


class OrderDetails(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        Merchandise,
        on_delete=models.CASCADE
    )
    quantity = models.FloatField(
        validators=[MinValueValidator(0)],
        default=0,
    )

    class Meta:
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказе'

    def __str__(self):
        return f"{self.order.user.username} {self.product.name}"

Final/istore/forms.py
# TODO: Сделать форму для просмотра и заказа товара
# TODO: Подключить форму просмотра товара на страницы: первая, каталог, просмотр товара

Final/istore/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

from users.models import User
from .models import Comment, Article
from .models import Merchandise
from .models import Order, OrderDetails


def index_view(request):
    template_name = 'istore\\index.html'
    context = {
        "articles": Article.objects.all().order_by("-creation_date")
    }

    return render(request, template_name, context)


PRODUCTS_PER_PAGE = 2


def catalog_view(request, cat_id: int = 0):
    template_name = 'istore\\catalog.html'

    products_all = Merchandise.objects.all().filter(category_id=cat_id)
    paginator = Paginator(products_all, PRODUCTS_PER_PAGE)

    current_page = request.GET.get('page', 1)
    products = paginator.get_page(current_page)

    prev_page_url, next_page_url = None, None
    if products.has_next():
        next_page_url = f"?page={products.next_page_number()}"
    if products.has_previous():
        prev_page_url = f"?page={products.previous_page_number()}"

    context = {
        "products": products,
        "next": next_page_url,
        "prev": prev_page_url,
    }

    return render(request, template_name, context)


def product_view(request, slug):
    # TODO: add anonymous comments
    template_name = 'istore\\product.html'
    product = Merchandise.objects.get(slug=slug)
    context = {
        'product': product,
        'comments': Comment.objects.all().filter(product=product)
    }

    return render(request, template_name, context)


@login_required
def add_to_cart(request, slug):
    prod = Merchandise.objects.all().filter(slug=slug)
    print(prod)
    if len(prod) == 1:
        order, created = Order.objects.get_or_create(user=request.user, active=True)
        order_det, created = OrderDetails.objects.get_or_create(order=order, product=prod[0])
        order_det.quantity += 1
        order_det.save()
    return redirect('cart')


@login_required
def buy_all(request, order_id):
    order = Order.objects.get(id=order_id)
    order.active = False
    order.save()
    return redirect('cart')


@login_required
def cart_view(request):
    template_name = "istore\\cart.html"
    context = {}
    user = User.objects.get(email=request.user)
    order = Order.objects.all().filter(user=user)
    order = order.filter(active=True)
    print(order)
    if order:
        prods_in_order = OrderDetails.objects.all().filter(order=order[0])
        context['prods_in_order'] = prods_in_order
        context['order'] = order[0]

    return render(request, template_name, context)

Final/templates/istore/cart.html
{% extends "istore\\../base.html" %}
{% load static %}

{% block title %}iStore{% endblock %}
{% block main %}

    <!-- Example row of columns -->
    {% if prods_in_order|length > 0 %}
        <div class="row">
            <div class="col-lg-6 col-md-9 col-sm-12 order-md-2 mb-4">
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Ваша корзина</span>
                    <span class="badge badge-secondary badge-pill">{{ prods_in_order|length }}</span>
                </h4>
                <ul class="list-group mb-3">
                    {% for prod in prods_in_order %}
                        <li class="list-group-item d-flex justify-content-between lh-condensed">
                            <div>
                                <h6 class="my-0">{{ prod.product.name }}</h6>
                                <small class="text-muted">{{ prod.product.description }}</small>
                            </div>
                            <span class="text-muted">{{ prod.quantity }}</span>
                        </li>
                    {% endfor %}
                </ul>
                <form class="card p-2" action="{% url 'buy_all' order.id %}">
                    <button type="submit" class="btn btn-secondary">Заказать</button>
                </form>
            </div>
        </div>
    {% else %}
        {% include 'empty_list.html' with msg='В корзине пока ничего нет!' %}
    {% endif %}

{% endblock %}

Final/templates/istore/catalog.html
{% extends "istore\\../base.html" %}
{% load static %}

{% block title %}iStore{% endblock %}
{% block main %}

    <!-- Example row of columns -->
    {% if products|length > 0 %}
        <div class="container mb-5">
            <div class="row">
                {% for prod in products %}
                    <div class="col-md-4">
                        <h2>{{ prod.name }}</h2>
                        <a href="{% url 'product_view' slug=prod.slug %}">
                            <img src="/{{ prod.picture }}" alt="{{ prod.name }}" width="180">
                        </a>

                        <form action="{% url 'add_to_cart' prod.slug %}">
                            <input type="submit" class="btn btn-secondary" value="Добавить в корзину »">
                        </form>
                    </div>
                {% endfor %}
            </div>
            {% if prev %}<a href="{{ prev }}">⟵</a>{% endif %}
            {% if next %}<a href="{{ next }}">⟶</a>{% endif %}
        </div> <!-- /container -->
    {% else %}
        {% include 'empty_list.html' with msg='Тут пока ничего нет!' %}
    {% endif %}

{% endblock %}

Final/templates/istore/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}iStore{% endblock %}
{% block main %}
    {% for article in articles %}
        <div class="jumbotron">
            <div class="container">
                <h1 class="display-4">{{ article.title }}</h1>
                <p>{{ article.text }}</p>
            </div>
        </div>

        <div class="container mb-5">
            <!-- Example row of columns -->
            <div class="row">
                {% for prod in article.merch.all %}
                    <div class="col-md-4">
                        <h2>{{ prod.name }}</h2>
                        <a href="{% url 'product_view' slug=prod.slug %}">
                            <img src="{{ prod.picture }}" alt="{{ prod.name }}" width="180">
                        </a>

                        <form action="{% url 'add_to_cart' prod.slug %}">
                            <input type="submit" class="btn btn-secondary" value="Добавить в корзину »">
                        </form>
                    </div>
                {% endfor %}
            </div>
        </div> <!-- /container -->

    {% endfor %}




{% endblock %}

Final/templates/istore/product.html
{% extends "istore\\../base.html" %}
{% load static %}

{% block title %}iStore{% endblock %}
{% block main %}

    <div class="container mt-3">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-12">
                <h2>{{ product.name }}</h2>

                <img src="/{{ product.picture }}" alt="{{ product.name }}" width="120">

                <p>{{ product.price }}</p>
                <p>{{ product.description }}</p>

                <a href="{% url 'add_to_cart' product.slug %}" methods="POST">Добавить в корзину</a>

                {#        <form method="post" action="./cart/">#}
                {#          <input type="hidden" name="csrfmiddlewaretoken"#}
                {#                 value="N4vcBqzjoYkU7OTDuAT8hq8srpvYX44nJsswuP7e3EYg0Hq8DgxuR0eiXWbSr5RZ">#}
                {#          <input type="hidden" name="merchandise_id" value="1">#}
                {#          <input type="submit" class="btn btn-secondary" value="Добавить в корзину »">#}
                {#        </form>#}

            </div>
        </div>

        <hr>

        {% if comments|length == 0 %}
            {% include 'empty_list.html' with msg='Отзывов пока нет' %}
        {% else %}
            {% for comment in comments %}
                {{ comment.get_rating_display }}
                <span>{{ comment.author }}</span>
                <p> {{ comment.comment_text }} </p>
            {% endfor %}
        {% endif %}

        <hr>

        {#    <div class="row">#}
        {#      <div class="col-lg-6 col-md-8 col-sm-12">#}
        {#        <h4>Оставте отзыв:</h4>#}
        {##}
        {#        <form action="./merch/1/feedback" method="post">#}
        {#          <input type="hidden" name="csrfmiddlewaretoken"#}
        {#                 value="N4vcBqzjoYkU7OTDuAT8hq8srpvYX44nJsswuP7e3EYg0Hq8DgxuR0eiXWbSr5RZ">#}
        {#          <div class="form-group">#}
        {#            <label for="name">Имя</label>#}
        {#            <input type="text" class="form-control" id="name" aria-describedby="nameHelp"#}
        {#                   placeholder="Представтесь" name="name" data-cip-id="name">#}
        {#          </div>#}
        {#          <div class="form-group">#}
        {#            <label for="content">Содержание</label>#}
        {#            <textarea class="form-control" id="content" placeholder="Содержание"#}
        {#                      name="description"></textarea>#}
        {#          </div>#}
        {##}
        {#          <div class="form-check">#}
        {#            <input class="form-check-input" type="radio" name="mark" id="mark1" value="1">#}
        {#            <label class="form-check-label" for="mark1">#}
        {#              1#}
        {#            </label>#}
        {#          </div>#}
        {##}
        {#          <div class="form-check">#}
        {#            <input class="form-check-input" type="radio" name="mark" id="mark2" value="2">#}
        {#            <label class="form-check-label" for="mark2">#}
        {#              2#}
        {#            </label>#}
        {#          </div>#}
        {##}
        {#          <div class="form-check">#}
        {#            <input class="form-check-input" type="radio" name="mark" id="mark3" value="3">#}
        {#            <label class="form-check-label" for="mark3">#}
        {#              3#}
        {#            </label>#}
        {#          </div>#}
        {##}
        {#          <div class="form-check">#}
        {#            <input class="form-check-input" type="radio" name="mark" id="mark4" value="4">#}
        {#            <label class="form-check-label" for="mark4">#}
        {#              4#}
        {#            </label>#}
        {#          </div>#}
        {##}
        {#          <div class="form-check">#}
        {#            <input class="form-check-input" type="radio" name="mark" id="mark5" value="5">#}
        {#            <label class="form-check-label" for="mark5">#}
        {#              5#}
        {#            </label>#}
        {#          </div>#}
        {##}
        {#          <button type="submit" class="btn btn-primary">Оставить</button>#}
        {#        </form>#}
        {#      </div>#}
        {#    </div>#}
        {##}
        {#  </div> <!-- /container -->#}

{% endblock %}